# Completá cada bloque añadiendo los except específicos necesarios
# (no usar except hasta atrapar todos los errores presentes en el ejercicio)

try:
    def funcion(z):
        return z.upper()

    valor = funcion(123, 456)
    print("Programa correcto")
    
#Completar aquí